[build-system]
requires = ["setuptools>=64"]
build-backend = "build_backend"
backend-path = ["."]

[project]
name = "video-auto-editor"
version = "4.7.0"
description = "Live video clip generation CLI."
requires-python = ">=3.10"

[project.scripts]
video-auto-editor = "video_auto_editor.cli:main"

[tool.setuptools.packages.find]
include = ["video_auto_editor", "video_auto_editor.*"]
namespaces = false

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]
