"""持久化脱敏运行诊断包。"""

from ._facts import Facts
from ._failure import DiagnosticsFailure
from ._model import (
    ArtifactRole,
    CacheNamespace,
    CacheOutcome,
    CertifiedPlatform,
    DeliveryBuildState,
    DeliveryVerificationState,
    DiagnosticFinalization,
    DiagnosticPackageSnapshot,
    ExternalDataCategory,
    ExternalRequestOutcome,
    InterruptionSignal,
    OperationKind,
    OperationOutcome,
    PreflightOutcome,
    ProviderCapability,
    ProviderTransport,
    PublicationState,
    RecoveredNoticeKind,
    RetryKind,
    ResultKind,
    RunOutcome,
    StageOutcome,
    ZeroRequestReason,
)
from ._reader import (
    DiagnosticPackageReader,
    DiagnosticPackageReadReason,
    DiagnosticPackageReadResult,
    DiagnosticPackageReadState,
)
from ._session import RunDiagnostics

__all__ = [
    "ArtifactRole",
    "CacheNamespace",
    "CacheOutcome",
    "CertifiedPlatform",
    "DeliveryBuildState",
    "DeliveryVerificationState",
    "DiagnosticFinalization",
    "DiagnosticsFailure",
    "DiagnosticPackageReader",
    "DiagnosticPackageReadReason",
    "DiagnosticPackageReadResult",
    "DiagnosticPackageReadState",
    "DiagnosticPackageSnapshot",
    "ExternalDataCategory",
    "ExternalRequestOutcome",
    "Facts",
    "InterruptionSignal",
    "OperationKind",
    "OperationOutcome",
    "PreflightOutcome",
    "ProviderCapability",
    "ProviderTransport",
    "PublicationState",
    "RecoveredNoticeKind",
    "RetryKind",
    "ResultKind",
    "RunDiagnostics",
    "RunOutcome",
    "StageOutcome",
    "ZeroRequestReason",
]
