"""全局默认配置。"""

CONFIG = {
    "silence_noise": -30,
    "silence_duration": 0.8,
    "min_score": 90,
    "min_duration": 15,
    "buffer_start": 1,
    "buffer_end": 3,
    "crf": 18,
    "preset": "fast",
    "audio_bitrate": "192k",
    "penalty_repeat": 5,
    "penalty_stutter": 3,
    "penalty_interrupt": 10,
    "bonus_natural_end": 5,
    "bonus_completeness_max": 3,
    "duplicate_threshold": 0.7,
    "min_clip_duration": 30,
    "max_clip_duration": 180,
    "target_clip_duration": 90,
    "topic_overlap_seconds": 15,
    "context_expand_before": 12,
    "context_expand_after": 8,
    "max_clips": 5,
    "temporary_protective_max_clips": 5,
    "allow_unreviewed_export": False,
    "min_clip_gap_seconds": 5,
    "export_subtitles": True,
    "live_report_name": "拆条报告.md",
    "asr_provider": "stepaudio",
    "asr_model": "stepaudio-2.5-asr",
    "asr_timeout": 120,
    "asr_language": "zh",
    "asr_max_upload_bytes": 200 * 1024 * 1024,
    "asr_shard_seconds": 600,
    "asr_audio_sample_rate": 16000,
    "asr_audio_channels": 1,
    "asr_audio_format": "wav",
    "asr_retry_attempts": 3,
    "asr_retry_backoff_seconds": 1.0,
    "stepfun_api_key_env": "STEPFUN_API_KEY",
    "stepfun_base_url_env": "STEPFUN_BASE_URL",
    "stepfun_base_url": "https://api.stepfun.com/v1",
    "whisper_model": "small",
    "whisper_language": "zh",
    "whisper_timeout": 120,
    "whisper_output_format": "txt",
    "whisper_sample_rate": 16000,
    "whisper_channels": 1,
}
